### ISSUE TITLE
Tests execution order changed for existing suits after updating unicorn libs

### ISSUE THREAD

**Issue by anubhav123455** [Unicorn-TAF/test-adapter#7]
Hi Team,
We recently updated unicorn libraries and after that Tests execution order has changed for almost all the suits. And because of this almost all test suits started failing due to dependency on previous test. Same behavior is observed in both local and remote runs 
**example 1:-**

Before update test execution:-
Suite1:-
1. [Preparation]
2. [Create document larger than 6 Mb]
3. [Download document larger than 6 Mb]

After update  test execution:-
1. [Preparation]
2. [Download document larger than 6 Mb]
3. [Create document larger than 6 Mb]

**Example2**:-
PASSED{Before update test execution:-}

1.   Verify Create New Fund During CapTables Import Workflow
2.   Verify Create New Security During CapT Import Workflow
3.   Verify Edit Security During CapT Import Workflow
4.   Verify Edit Fund During CapT Import Workflow
5.   Verify Create Asset From Upload File And Choose Asset

FAILED{After update  test execution}:-

1.   Verify Edit Fund During CapT Import Workflow
2.   Verify Create Asset From Upload File And Choose Asset
3.   Verify Edit Security During CapT Import Workflow
4.   Verify Create New Fund During CapT Import Workflow
5.   Verify Create New Security During CapT Import Workflow

Older Versions when working fine:-
  Unicorn.Taf.Api  - 1.0.0
  Unicorn.Taf.Core - 3.0.0
  Unicorn.TestAdapter - 3.0.0
  Unicorn.UI.Core - 3.0.0
  
  Updated newer versions when test execution changed and started failing:-
   Unicorn.Taf.Api  - 1.1.0
  Unicorn.Taf.Core - 3.2.0
  Unicorn.TestAdapter - 3.1.0
  Unicorn.UI.Core - 3.1.0

The above issue can be managed by using order attribute "[Order(_orderNumber_)]" but it is not possible to update all the existing tests with this attribute.

Please let me know if any further logs are required.

Thanks

**Comment by anubhav123455** [comment]
Older Versions when working fine:-
 <package id="Unicorn.Taf.Api" version="1.0.0" targetFramework="net472" />
  <package id="Unicorn.Taf.Core" version="3.0.0" targetFramework="net472" />
  <package id="Unicorn.TestAdapter" version="3.0.0" targetFramework="net472" />
  <package id="Unicorn.UI.Core" version="3.0.0" targetFramework="net472" />
  
  Updated newer versions when test execution changed and started failing:-
  <package id="Unicorn.Taf.Api" version="1.1.0" targetFramework="net472" />
  <package id="Unicorn.Taf.Core" version="3.2.0" targetFramework="net472" />
  <package id="Unicorn.TestAdapter" version="3.1.0" targetFramework="net472" />
  <package id="Unicorn.UI.Core" version="3.1.0" targetFramework="net472" />

**Comment by dobriyanchik** [comment]
Possibly the cause of the issue is new .NET version used for binaries building. If to tell the truth until .NET 7 "right" order of methods taken by reflection is not guaranteed (and it's the same for all other unit frameworks)

Potentially it could be solved by building with previously used .NET version.
Will investigate it closer

**Comment by dobriyanchik** [comment]
As I mentioned before and as per https://learn.microsoft.com/en-us/dotnet/api/system.type.getmethods
![image](https://github.com/user-attachments/assets/c5a67703-509e-4eb9-b12c-068e4d6f797f)

This is not an issue of the adapter or the taf.core. 

Ideally automated tests should be independent of each other in majority of cases (of course there could be cases when predefined order really necessary). Independent tests give several different benefits:
 - absence of non-obvious fail reasons because of issues in other tests
 - ability to quickly debug/re-run tests without necessity of running other tests before
 - more flexibility in targeted tests run as single individual test could be filtered for the run

If for some cases the order is still very important it's better to use `Alphabetical` execution mode and to artifically order tests within test suite or to use `Order` attribute. Those will guarantee ordered run unlike declaration order
